# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_billbil.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_billbil.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b(
    '\n\x13hello_billbil.proto\x12\x04test\"*\n\rHelloDeWeiReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1f\n\rHelloDeweiRsp\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x06\x42ibili\x12\x38\n\nHelloDewei\x12\x13.test.HelloDeWeiReq\x1a\x13.test.HelloDeweiRsp\"\x00\x62\x06proto3')
)

_HELLODEWEIREQ = _descriptor.Descriptor(
  name='HelloDeWeiReq',
  full_name='test.HelloDeWeiReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.HelloDeWeiReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='test.HelloDeWeiReq.age', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=71,
)

_HELLODEWEIRSP = _descriptor.Descriptor(
  name='HelloDeweiRsp',
  full_name='test.HelloDeweiRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.HelloDeweiRsp.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['HelloDeWeiReq'] = _HELLODEWEIREQ
DESCRIPTOR.message_types_by_name['HelloDeweiRsp'] = _HELLODEWEIRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloDeWeiReq = _reflection.GeneratedProtocolMessageType('HelloDeWeiReq', (_message.Message,), {
  'DESCRIPTOR': _HELLODEWEIREQ,
  '__module__': 'hello_billbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDeWeiReq)
})
_sym_db.RegisterMessage(HelloDeWeiReq)

HelloDeweiRsp = _reflection.GeneratedProtocolMessageType('HelloDeweiRsp', (_message.Message,), {
  'DESCRIPTOR': _HELLODEWEIRSP,
  '__module__': 'hello_billbil_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloDeweiRsp)
})
_sym_db.RegisterMessage(HelloDeweiRsp)

_BIBILI = _descriptor.ServiceDescriptor(
  name='Bibili',
  full_name='test.Bibili',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=172,
  methods=[
    _descriptor.MethodDescriptor(
      name='HelloDewei',
      full_name='test.Bibili.HelloDewei',
      index=0,
      containing_service=None,
      input_type=_HELLODEWEIREQ,
      output_type=_HELLODEWEIRSP,
      serialized_options=None,
    ),
  ])
_sym_db.RegisterServiceDescriptor(_BIBILI)

DESCRIPTOR.services_by_name['Bibili'] = _BIBILI

# @@protoc_insertion_point(module_scope)
